name: Båtliv genom åren
favicon: null
layout_spectrum: 0.25768
typography_spectrum: 0.30340890120714903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2666415621060878
  lightness: 0.2525966956745833
  saturation: 0.7244053352624178
  rhythmicContrast: 0.9540030716452748
purpose: []
